import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getCurrentUser } from "@/lib/auth/session";
import { LogoutButton } from "./components/LogoutButton";
import { prisma } from "@/lib/db";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const unseenCount = user ? await (prisma as any).notification.count({ where: { userId: user.id, seen: false } }) : 0;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b">
          <div className="mx-auto max-w-4xl px-4 h-14 flex items-center justify-between">
            <nav className="flex items-center gap-4 text-sm">
              <Link href="/" className="font-semibold">COSE Community</Link>
              <Link href="/communities">Communities</Link>
              <Link href="/debates">Debates</Link>
            </nav>
            <div className="flex items-center gap-3 text-sm">
              <form action="/search" className="hidden sm:block">
                <input name="q" placeholder="Search..." className="border rounded px-2 py-1 text-sm" />
              </form>
              {user ? (
                <>
                  <Link href={`/u/${user.username}`} className="text-gray-600 underline">{user.username}</Link>
                  <Link href="/notifications" className="px-3 py-1.5 rounded border hover:bg-gray-100 dark:hover:bg-gray-900 relative">
                    Notifications{unseenCount > 0 && (<span className="ml-2 text-xs inline-flex items-center justify-center min-w-5 h-5 px-1 rounded-full bg-red-600 text-white">{unseenCount}</span>)}
                  </Link>
                  <Link href="/me" className="px-3 py-1.5 rounded border hover:bg-gray-100 dark:hover:bg-gray-900">My profile</Link>
                  {user.role === "ADMIN" && (
                    <Link href="/admin" className="px-3 py-1.5 rounded border hover:bg-gray-100 dark:hover:bg-gray-900">Admin</Link>
                  )}
                  <LogoutButton />
                </>
              ) : (
                <>
                  <Link href="/login" className="px-3 py-1.5 rounded border hover:bg-gray-100 dark:hover:bg-gray-900">Login</Link>
                  <Link href="/register" className="px-3 py-1.5 rounded bg-black text-white dark:bg-white dark:text-black">Register</Link>
                </>
              )}
            </div>
          </div>
        </header>
        <main className="mx-auto max-w-4xl px-4 py-6">
          {children}
        </main>
      </body>
    </html>
  );
}
