import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getCurrentUser } from "@/lib/auth/session";
import { LogoutButton } from "./components/LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b">
          <div className="mx-auto max-w-4xl px-4 h-14 flex items-center justify-between">
            <nav className="flex items-center gap-4 text-sm">
              <Link href="/" className="font-semibold">COSE Community</Link>
              <Link href="/communities">Communities</Link>
              <Link href="/debates">Debates</Link>
            </nav>
            <div className="flex items-center gap-3 text-sm">
              {user ? (
                <>
                  <Link href={`/u/${user.username}`} className="text-gray-600 underline">{user.username}</Link>
                  <Link href="/me" className="px-3 py-1.5 rounded border hover:bg-gray-100 dark:hover:bg-gray-900">My profile</Link>
                  <LogoutButton />
                </>
              ) : (
                <>
                  <Link href="/login" className="px-3 py-1.5 rounded border hover:bg-gray-100 dark:hover:bg-gray-900">Login</Link>
                  <Link href="/register" className="px-3 py-1.5 rounded bg-black text-white dark:bg-white dark:text-black">Register</Link>
                </>
              )}
            </div>
          </div>
        </header>
        <main className="mx-auto max-w-4xl px-4 py-6">
          {children}
        </main>
      </body>
    </html>
  );
}
