// 정당 이름 매핑 (영어 -> 한글)
export const partyNameMap: Record<string, string> = {
  'Democratic': '더불어민주당',
  'People_Power': '국민의힘',
  'People Power': '국민의힘',
  'Rebuilding_Korea': '조국혁신당',
  'Rebuilding Korea': '조국혁신당',
  'The_Progressive': '진보당',
  'The Progressive': '진보당',
  'Reform': '개혁신당',
  'Basic_Income': '기본소득당',
  'Basic Income': '기본소득당',
  'The Social Democratic': '사회민주당',
  'The_Social_Democratic': '사회민주당',
  'The Social_Democratic': '사회민주당',
  'The_Social Democratic': '사회민주당',
  'Minor': '기타',
  'None': '없음',
  // 소문자 변형도 지원
  'democratic': '더불어민주당',
  'people_power': '국민의힘',
  'people power': '국민의힘',
  'people_Power': '국민의힘',
  'people Power': '국민의힘',
  'People_power': '국민의힘',
  'People power': '국민의힘',
  'rebuilding_korea': '조국혁신당',
  'rebuilding korea': '조국혁신당',
  'rebuilding_Korea': '조국혁신당',
  'rebuilding Korea': '조국혁신당',
  'Rebuilding_korea': '조국혁신당',
  'Rebuilding korea': '조국혁신당',
  'the_progressive': '진보당',
  'the progressive': '진보당',
  'the_Progressive': '진보당',
  'the Progressive': '진보당',
  'The_progressive': '진보당',
  'The progressive': '진보당',
  'Reform': '개혁신당',
  'basic_income': '기본소득당',
  'basic income': '기본소득당',
  'basic_Income': '기본소득당',
  'basic Income': '기본소득당',
  'Basic_income': '기본소득당',
  'Basic income': '기본소득당',
  'the social democratic': '사회민주당',
  'the_social_democratic': '사회민주당',
  'the social Democratic': '사회민주당',
  'the_social_Democratic': '사회민주당',
  'the Social democratic': '사회민주당',
  'the_Social_democratic': '사회민주당',
  'The social democratic': '사회민주당',
  'The_social_democratic': '사회민주당',
  'the Social Democratic': '사회민주당',
  'the_Social_Democratic': '사회민주당',
  'The social Democratic': '사회민주당',
  'The_social_Democratic': '사회민주당',
  'The Social democratic': '사회민주당',
  'The_Social_democratic': '사회민주당',
  'minor': '기타',
  'none': '없음',
}

export const getPartyName = (party: string | null | undefined): string => {
  if (!party) return ''
  return partyNameMap[party] || party
}

